package hibernatexml;
// Generated Feb 1, 2019 10:05:11 AM by Hibernate Tools 4.3.1



/**
 * Basiccrud generated by hbm2java
 */
public class Basiccrud  implements java.io.Serializable {


     private Integer id;
     private String basicRandomdata;

    public Basiccrud() {
    }

    public Basiccrud(String basicRandomdata) {
       this.basicRandomdata = basicRandomdata;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getBasicRandomdata() {
        return this.basicRandomdata;
    }
    
    public void setBasicRandomdata(String basicRandomdata) {
        this.basicRandomdata = basicRandomdata;
    }




}


