package hibernatexml;
// Generated Feb 1, 2019 10:05:11 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * City generated by hbm2java
 */
public class City  implements java.io.Serializable {


     private Integer id;
     private String cityName;
     private Set userlists = new HashSet(0);

    public City() {
    }

	
    public City(String cityName) {
        this.cityName = cityName;
    }
    public City(String cityName, Set userlists) {
       this.cityName = cityName;
       this.userlists = userlists;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getCityName() {
        return this.cityName;
    }
    
    public void setCityName(String cityName) {
        this.cityName = cityName;
    }
    public Set getUserlists() {
        return this.userlists;
    }
    
    public void setUserlists(Set userlists) {
        this.userlists = userlists;
    }

    @Override
    public String toString() {
        return "City{" + "id=" + id + ", cityName=" + cityName + ", userlists=" + userlists + '}';
    }




}


