package hibernatexml;
// Generated Feb 1, 2019 10:05:11 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Userlist generated by hbm2java
 */
public class Userlist  implements java.io.Serializable {


     private Integer id;
     private City city;
     private String userlistUsername;
     private String userlistPassword;
     private String userlistSex;
     private Set advancedcruds = new HashSet(0);

    public Userlist() {
    }

	
    public Userlist(City city, String userlistUsername, String userlistPassword, String userlistSex) {
        this.city = city;
        this.userlistUsername = userlistUsername;
        this.userlistPassword = userlistPassword;
        this.userlistSex = userlistSex;
    }
    public Userlist(City city, String userlistUsername, String userlistPassword, String userlistSex, Set advancedcruds) {
       this.city = city;
       this.userlistUsername = userlistUsername;
       this.userlistPassword = userlistPassword;
       this.userlistSex = userlistSex;
       this.advancedcruds = advancedcruds;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public City getCity() {
        return this.city;
    }
    
    public void setCity(City city) {
        this.city = city;
    }
    public String getUserlistUsername() {
        return this.userlistUsername;
    }
    
    public void setUserlistUsername(String userlistUsername) {
        this.userlistUsername = userlistUsername;
    }
    public String getUserlistPassword() {
        return this.userlistPassword;
    }
    
    public void setUserlistPassword(String userlistPassword) {
        this.userlistPassword = userlistPassword;
    }
    public String getUserlistSex() {
        return this.userlistSex;
    }
    
    public void setUserlistSex(String userlistSex) {
        this.userlistSex = userlistSex;
    }
    public Set getAdvancedcruds() {
        return this.advancedcruds;
    }
    
    public void setAdvancedcruds(Set advancedcruds) {
        this.advancedcruds = advancedcruds;
    }




}


